<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/02/03 09:14:58

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=mysql.tatai.es;dbname=tatai_jobeet',
  'username' => 'tatai_jobeet',
  'password' => 'jobeet_pruebas',
  'name' => 'doctrine',
)),);
